base_catalog: common_data_platform
catalog_suffix: _uat

schemas:
  - raw
  - foundation
  - trusted
  - platform

volumes:
  - name: source_files
    schema: raw

  - name: documents
    schema: raw

  - name: checkpoints
    schema: platform